In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline 
sns.set(color_codes=True)

In [11]:
df = pd.read_csv("20260327_Notas_y_Egresados_Enseñanza_Media_2025_PUBL.csv")

In [12]:
df.head()

,AGNO,RBD,DGV_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,NOM_DEPROV_RBD,...,COD_GRADO,COD_DEPE,COD_DEPE2,RURAL_RBD,MRUN,MRUN_IPE,PROM_NOTAS_ALU,ORIGEN,ENSE_COMPLETA,MARCA_EGRESO
0,2025,2308,6.0,6.0,LGBO,61.0,6115.0,RENGO,61.0,CACHAPOAL,...,4,3.0,2.0,0.0,89,NaN,61.0,SIGE,1,1
1,2025,17810,1.0,8.0,BBIO,82.0,8203.0,CAÑETE,84.0,ARAUCO,...,4,3.0,2.0,0.0,129,NaN,60.0,SIGE,1,1
2,2025,12305,6.0,5.0,VALPO,58.0,5804.0,VILLA ALEMANA,53.0,VALPARAÍSO,...,4,3.0,2.0,0.0,258,NaN,53.0,SIGE,1,1
3,2025,8005,5.0,10.0,LAGOS,102.0,10201.0,CASTRO,102.0,CHILOÉ,...,4,6.0,5.0,0.0,259,NaN,57.0,SIGE,1,1
4,2025,60,4.0,15.0,AYP,151.0,15101.0,ARICA,151.0,ARICA,...,4,3.0,2.0,0.0,326,NaN,63.0,SIGE,1,1

In [13]:
df.describe()

,AGNO,RBD,DGV_RBD,COD_REG_RBD,COD_PRO_RBD,COD_COM_RBD,COD_DEPROV_RBD,COD_ENSE,COD_GRADO,COD_DEPE,COD_DEPE2,RURAL_RBD,MRUN,MRUN_IPE,PROM_NOTAS_ALU,ENSE_COMPLETA,MARCA_EGRESO
count,290825.0,290825.000000,281940.000000,281939.000000,281939.000000,281939.000000,281939.000000,290825.000000,290825.000000,281939.000000,281939.000000,281939.000000,2.908250e+05,1.507500e+04,282186.000000,290825.0,290825.000000
mean,2025.0,12049.609280,4.457062,9.375209,95.691845,9575.524298,94.020579,376.690250,3.933066,3.246596,2.314089,0.033380,1.396640e+07,2.625776e+07,59.951475,1.0,0.967441
std,0.0,9566.592907,2.879106,4.010426,39.899787,3992.667939,39.258032,102.951697,0.390752,1.342484,1.249776,0.179626,8.171321e+06,1.821352e+06,6.168528,0.0,0.177480
min,2025.0,0.000000,0.000000,1.000000,11.000000,1101.000000,11.000000,310.000000,1.000000,1.000000,1.000000,0.000000,8.900000e+01,1.301430e+05,18.000000,1.0,0.000000
25%,2025.0,4277.000000,2.000000,6.000000,61.000000,6105.000000,61.000000,310.000000,4.000000,3.000000,2.000000,0.000000,6.948563e+06,2.560281e+07,56.000000,1.0,1.000000
50%,2025.0,9877.000000,4.000000,10.000000,101.000000,10101.000000,92.000000,310.000000,4.000000,3.000000,2.000000,0.000000,1.384935e+07,2.614468e+07,61.000000,1.0,1.000000
75%,2025.0,17833.000000,7.000000,13.000000,131.000000,13122.000000,133.000000,410.000000,4.000000,4.000000,3.000000,0.000000,2.080564e+07,2.719090e+07,65.000000,1.0,1.000000
max,2025.0,95850.000000,9.000000,16.000000,163.000000,16305.000000,151.000000,910.000000,4.000000,6.000000,5.000000,1.000000,2.848344e+07,2.848344e+07,70.000000,1.0,1.000000

In [ ]:
from